// Package docsgen generates living API documentation from the contract
// registry: one markdown page per contract (endpoints, methods, types) plus
// an index page linking all of them. acthur-prd.md §36 describes multiple
// doc-site targets (Astro, Nextra, README, OpenAPI); this package implements
// the target-agnostic markdown shape all of those would ultimately embed —
// per-contract API reference pages under docs/api/.
package docsgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/acthurhq/acthur/internal/contract"
	"github.com/acthurhq/acthur/internal/plugin"
)

// Generate renders one docs/api/<name>.md file per contract in reg, plus a
// docs/api/README.md index. Contracts are sorted by name then version so
// output is deterministic across runs with no source change.
func Generate(reg *contract.Registry) ([]plugin.GeneratedFile, error) {
	if reg == nil {
		return nil, fmt.Errorf("docsgen: contract registry is nil")
	}

	contracts := reg.All()
	sort.Slice(contracts, func(i, j int) bool {
		if contracts[i].Name != contracts[j].Name {
			return contracts[i].Name < contracts[j].Name
		}
		return contracts[i].Version < contracts[j].Version
	})

	files := make([]plugin.GeneratedFile, 0, len(contracts)+1)
	files = append(files, indexFile(contracts))
	for _, c := range contracts {
		files = append(files, contractFile(c))
	}
	return files, nil
}

func indexFile(contracts []*contract.Contract) plugin.GeneratedFile {
	var b strings.Builder
	b.WriteString("# API Reference\n\n")
	b.WriteString("Generated by `acthur generate docs` from the project's contract registry " +
		"(`contracts/*.contract.yml`). One page per contract — do not hand-edit; regenerate " +
		"after changing a contract instead.\n\n")

	if len(contracts) == 0 {
		b.WriteString("_No contracts declared under `contracts/`._\n")
	} else {
		b.WriteString("| Contract | Version | Transport | Endpoints |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, c := range contracts {
			fmt.Fprintf(&b, "| [%s](./%s) | %s | %s | %d |\n",
				c.Name, fileName(c), c.Version, c.Transport, len(c.Endpoints))
		}
	}

	return plugin.GeneratedFile{
		Path:      "docs/api/README.md",
		Content:   []byte(b.String()),
		Overwrite: true,
	}
}

func contractFile(c *contract.Contract) plugin.GeneratedFile {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", c.Name)
	fmt.Fprintf(&b, "Version `%s` · transport `%s`\n\n", c.Version, c.Transport)
	b.WriteString("Generated by `acthur generate docs` — do not hand-edit; regenerate instead.\n\n")

	writeEndpoints(&b, c)
	writeEvents(&b, c)
	writeTypes(&b, c)

	return plugin.GeneratedFile{
		Path:      "docs/api/" + fileName(c),
		Content:   []byte(b.String()),
		Overwrite: true,
	}
}

func fileName(c *contract.Contract) string {
	return c.Name + ".md"
}

func writeEndpoints(b *strings.Builder, c *contract.Contract) {
	b.WriteString("## Endpoints\n\n")
	if len(c.Endpoints) == 0 {
		b.WriteString("_No endpoints declared._\n\n")
		return
	}
	for _, e := range c.Endpoints {
		title := e.ID
		if e.Method != "" || e.Path != "" {
			title = fmt.Sprintf("%s %s", e.Method, e.Path)
		}
		fmt.Fprintf(b, "### %s\n\n", title)
		if e.ID != "" {
			fmt.Fprintf(b, "- **ID**: `%s`\n", e.ID)
		}
		if e.Auth != "" {
			fmt.Fprintf(b, "- **Auth**: %s\n", e.Auth)
		}
		if len(e.Roles) > 0 {
			fmt.Fprintf(b, "- **Roles**: %s\n", strings.Join(e.Roles, ", "))
		}
		if e.RateLimit.Max > 0 {
			fmt.Fprintf(b, "- **Rate limit**: %d / %s\n", e.RateLimit.Max, e.RateLimit.Window)
		}
		if e.Deprecated {
			dep := "- **Deprecated**"
			if e.DeprecatedAt != "" {
				dep += fmt.Sprintf(" (since %s)", e.DeprecatedAt)
			}
			if e.SunsetAt != "" {
				dep += fmt.Sprintf(", sunset %s", e.SunsetAt)
			}
			b.WriteString(dep + "\n")
		}
		if e.Streaming != "" {
			fmt.Fprintf(b, "- **Streaming**: %s\n", e.Streaming)
		}
		b.WriteString("\n")

		writeFieldMap(b, "Input", e.Input)
		writeFieldMap(b, "Output", e.Output)

		if len(e.Errors) > 0 {
			b.WriteString("**Errors**\n\n")
			b.WriteString("| Status | Code | Message |\n|---|---|---|\n")
			for _, err := range e.Errors {
				fmt.Fprintf(b, "| %d | `%s` | %s |\n", err.Status, err.Code, err.Message)
			}
			b.WriteString("\n")
		}
	}
}

func writeEvents(b *strings.Builder, c *contract.Contract) {
	if len(c.Events) == 0 {
		return
	}
	b.WriteString("## Events\n\n")
	for _, ev := range c.Events {
		fmt.Fprintf(b, "### %s\n\n", ev.ID)
		writeFieldMap(b, "Payload", ev.Payload)
	}
}

func writeTypes(b *strings.Builder, c *contract.Contract) {
	b.WriteString("## Types\n\n")
	if len(c.Types) == 0 {
		b.WriteString("_No shared types declared._\n\n")
		return
	}
	names := make([]string, 0, len(c.Types))
	for name := range c.Types {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(b, "### %s\n\n", name)
		writeFieldMap(b, "", c.Types[name].Fields)
	}
}

// writeFieldMap renders a field:type map as a two-column table sorted by
// field name, under an optional bold label. Renders nothing for an empty map.
func writeFieldMap(b *strings.Builder, label string, fields map[string]string) {
	if len(fields) == 0 {
		return
	}
	if label != "" {
		fmt.Fprintf(b, "**%s**\n\n", label)
	}
	b.WriteString("| Field | Type |\n|---|---|\n")
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(b, "| %s | `%s` |\n", name, fields[name])
	}
	b.WriteString("\n")
}
