// Package testplugin is the built-in "test" plugin: Phase 5's proof that a
// plugin's hook, command, and generator registrations all fire at the correct
// lifecycle points under the real kernel. It ships registered (blank-imported
// by the CLI) but is never part of a default plugin list — a project opts in
// with `plugins: [test]`.
package testplugin

import (
	"github.com/acthur/acthur/internal/plugin"
)

type testPlugin struct{}

func (testPlugin) Name() string        { return "test" }
func (testPlugin) Version() string     { return "0.1.0" }
func (testPlugin) DependsOn() []string { return nil }

func (testPlugin) Register(k plugin.KernelAPI) error {
	// Hook: announce every node that becomes healthy.
	k.OnEvent(plugin.EventAfterNodeHealthy, func(p plugin.EventPayload) {
		k.Log(plugin.LogInfo, "test-plugin: node %q is healthy", p.NodeID)
	})

	// Command: visible in `acthur --help`, runnable.
	k.RegisterCommand(plugin.CLICommand{
		Use:   "test-plugin",
		Short: "Prove the plugin system: prints a message and exits",
		Run: func(args []string) error {
			k.Log(plugin.LogInfo, "test-plugin: command executed (args: %v)", args)
			return nil
		},
	})

	// Generator target: registered for introspection; Phase 7 executes these.
	k.RegisterGenerator("test-plugin", generator{})
	return nil
}

type generator struct{}

func (generator) Generate(adapterName string, ctx plugin.GeneratorContext) ([]plugin.GeneratedFile, error) {
	return []plugin.GeneratedFile{{
		Path:    "TEST_PLUGIN.md",
		Content: []byte("generated by the test plugin\n"),
	}}, nil
}

func (generator) SupportedAdapters() []string { return []string{"*"} }

func init() {
	plugin.Register(testPlugin{})
}
