package gofiber

import (
	"fmt"
	"strings"
)

// emitHandler renders the fiber handlers: parse input (body or query),
// validate, call the service, map APIErrors to their declared statuses.
func emitHandler(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"errors\"\n\n\t\"github.com/gofiber/fiber/v2\"\n)\n\n", m.ContractFile, m.Package)

	b.WriteString(`// Handler serves the ` + m.Contract + ` contract's endpoints over fiber.
type Handler struct {
	Svc Service
}

// errorResponse maps a service error onto the contract's declared HTTP
// statuses; anything that is not an APIError becomes a 500.
func errorResponse(c *fiber.Ctx, err error) error {
	var apiErr *APIError
	if errors.As(err, &apiErr) {
		return c.Status(apiErr.Status).JSON(fiber.Map{"error": apiErr})
	}
	return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
		"error": fiber.Map{"code": "internal_error"},
	})
}

func validationFailed(c *fiber.Ctx, err error) error {
	return c.Status(fiber.StatusUnprocessableEntity).JSON(fiber.Map{
		"error": fiber.Map{"code": "validation_failed", "message": err.Error()},
	})
}

`)

	for _, e := range m.Endpoints {
		emitOneHandler(&b, e)
	}
	return []byte(b.String())
}

func emitOneHandler(b *strings.Builder, e endpointSpec) {
	// Document the endpoint's declared error mapping next to its handler.
	if len(e.Errors) > 0 {
		var docs []string
		for _, ce := range e.Errors {
			docs = append(docs, fmt.Sprintf("%d %s", ce.Status, ce.Code))
		}
		fmt.Fprintf(b, "// %s handles %s %s (declared errors: %s).\n", e.GoName, e.Method, e.Path, strings.Join(docs, ", "))
	} else {
		fmt.Fprintf(b, "// %s handles %s %s.\n", e.GoName, e.Method, e.Path)
	}
	fmt.Fprintf(b, "func (h *Handler) %s(c *fiber.Ctx) error {\n", e.GoName)

	for _, p := range e.PathParams {
		fmt.Fprintf(b, "\t%s := c.Params(%q)\n", p, p)
	}

	if len(e.Input) > 0 {
		fmt.Fprintf(b, "\tvar in %sInput\n", e.GoName)
		if e.FromBody {
			b.WriteString("\tif err := c.BodyParser(&in); err != nil {\n\t\treturn validationFailed(c, err)\n\t}\n")
		} else {
			b.WriteString("\tif err := c.QueryParser(&in); err != nil {\n\t\treturn validationFailed(c, err)\n\t}\n")
		}
		b.WriteString("\tif err := in.Validate(); err != nil {\n\t\treturn validationFailed(c, err)\n\t}\n")
	}

	call := fmt.Sprintf("h.Svc.%s(%s)", e.GoName, serviceCallArgs(e))
	if len(e.Output) > 0 {
		fmt.Fprintf(b, "\tout, err := %s\n\tif err != nil {\n\t\treturn errorResponse(c, err)\n\t}\n\treturn c.Status(%d).JSON(out)\n", call, e.SuccessCode)
	} else {
		fmt.Fprintf(b, "\tif err := %s; err != nil {\n\t\treturn errorResponse(c, err)\n\t}\n\treturn c.SendStatus(%d)\n", call, e.SuccessCode)
	}
	b.WriteString("}\n\n")
}

// emitRoutes renders Mount(app, db) plus the RequireAuth stub hook.
func emitRoutes(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"github.com/gofiber/fiber/v2\"\n\t\"github.com/jackc/pgx/v5/pgxpool\"\n)\n\n", m.ContractFile, m.Package)

	b.WriteString(`// RequireAuth guards endpoints the contract marks auth: required. It is a
// pass-through stub: replace it (or assign your auth middleware to it at
// startup) to enforce authentication — e.g. auth.RequireAuth from the auth
// plugin's generated package.
var RequireAuth fiber.Handler = func(c *fiber.Ctx) error { return c.Next() }

// Mount registers every ` + m.Contract + ` endpoint on app, wired to the
// generated service and repository skeletons.
func Mount(app *fiber.App, db *pgxpool.Pool) {
	MountWith(app, NewService(NewRepository(db)))
}

// MountWith registers the routes against a caller-supplied Service —
// used by tests and by callers replacing the generated skeleton.
func MountWith(app *fiber.App, svc Service) {
	h := &Handler{Svc: svc}
`)
	for _, e := range m.Endpoints {
		if e.AuthRequired {
			fmt.Fprintf(&b, "\tapp.%s(%q, RequireAuth, h.%s)\n", e.FiberMethod, e.Path, e.GoName)
		} else {
			fmt.Fprintf(&b, "\tapp.%s(%q, h.%s)\n", e.FiberMethod, e.Path, e.GoName)
		}
	}
	b.WriteString("}\n")
	return []byte(b.String())
}
