package gofiber

import (
	"fmt"
	"strings"
)

// validGoLiteral returns a Go literal satisfying the field's constraints,
// used in generated tests' happy paths.
func validGoLiteral(f fieldSpec) string {
	var lit string
	switch f.BaseType {
	case "email":
		lit = `"gen@example.com"`
	case "enum":
		lit = fmt.Sprintf("%q", f.Enum[0])
	case "int":
		lit = "int64(1)"
	case "bool":
		lit = "true"
	default:
		lit = `"x"`
	}
	if f.Optional {
		return "" // optional fields are simply omitted in happy paths
	}
	return lit
}

// validJSONValue returns a JSON value satisfying the field's constraints.
func validJSONValue(f fieldSpec) string {
	switch f.BaseType {
	case "email":
		return `"gen@example.com"`
	case "enum":
		return fmt.Sprintf("%q", f.Enum[0])
	case "int":
		return "1"
	case "bool":
		return "true"
	default:
		return `"x"`
	}
}

func validInputLiteral(e endpointSpec) string {
	var fields []string
	for _, f := range e.Input {
		lit := validGoLiteral(f)
		if lit == "" {
			continue
		}
		fields = append(fields, fmt.Sprintf("%s: %s", f.GoName, lit))
	}
	return fmt.Sprintf("%sInput{%s}", e.GoName, strings.Join(fields, ", "))
}

func validJSONBody(e endpointSpec) string {
	var fields []string
	for _, f := range e.Input {
		if f.Optional {
			continue
		}
		fields = append(fields, fmt.Sprintf("%q:%s", f.Name, validJSONValue(f)))
	}
	return "{" + strings.Join(fields, ",") + "}"
}

// emitDTOTest generates Validate tests: the happy path plus one failure per
// constrained field of every endpoint input.
func emitDTOTest(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"strings\"\n\t\"testing\"\n)\n\nfunc strptr(s string) *string { return &s }\n\nvar _ = strings.Repeat // used by max-length cases when present\nvar _ = strptr\n\n", m.ContractFile, m.Package)

	for _, e := range m.Endpoints {
		vf := validatedFields(e.Input)
		if len(vf) == 0 {
			continue
		}
		fmt.Fprintf(&b, "func Test%sInput_Validate(t *testing.T) {\n", e.GoName)
		fmt.Fprintf(&b, "\tvalid := %s\n\tif err := valid.Validate(); err != nil {\n\t\tt.Errorf(\"valid input should pass, got: %%v\", err)\n\t}\n\n", validInputLiteral(e))

		for _, f := range vf {
			set := func(expr string) string {
				if f.Optional {
					if f.GoType == "*string" {
						return fmt.Sprintf("\tin.%s = strptr(%s)\n", f.GoName, expr)
					}
					return fmt.Sprintf("\tv := %s\n\tin.%s = &v\n", expr, f.GoName)
				}
				return fmt.Sprintf("\tin.%s = %s\n", f.GoName, expr)
			}
			emitCase := func(label, expr string) {
				fmt.Fprintf(&b, "\t{\n\tin := valid\n%s\tif err := in.Validate(); err == nil {\n\t\tt.Errorf(\"%s: expected validation failure\")\n\t}\n\t}\n", set(expr), label)
			}
			if f.Required && !f.Optional {
				emitCase(f.Name+" required", `""`)
			}
			if f.MaxLen > 0 {
				emitCase(f.Name+" max length", fmt.Sprintf(`strings.Repeat("x", %d)`, f.MaxLen+1))
			}
			if f.BaseType == "email" {
				emitCase(f.Name+" email format", `"not-an-email"`)
			}
			if f.BaseType == "enum" {
				emitCase(f.Name+" enum membership", `"zzz_invalid_enum"`)
			}
		}
		b.WriteString("}\n\n")
	}
	return []byte(b.String())
}

// emitHandlerTest generates a fake service plus one happy-path request per
// endpoint and one validation-failure request.
func emitHandlerTest(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"context\"\n\t\"net/http/httptest\"\n\t\"strings\"\n\t\"testing\"\n\n\t\"github.com/gofiber/fiber/v2\"\n)\n\n", m.ContractFile, m.Package)

	// Fake service with canned successful outputs.
	b.WriteString("type fakeService struct{}\n\n")
	for _, e := range m.Endpoints {
		fmt.Fprintf(&b, "func (fakeService) %s {\n", serviceSig(e))
		if len(e.Output) > 0 {
			fmt.Fprintf(&b, "\treturn &%sOutput{}, nil\n", e.GoName)
		} else {
			b.WriteString("\treturn nil\n")
		}
		b.WriteString("}\n\n")
	}
	b.WriteString("var _ = context.Background\n\nfunc testApp() *fiber.App {\n\tapp := fiber.New()\n\tMountWith(app, fakeService{})\n\treturn app\n}\n\n")

	for _, e := range m.Endpoints {
		path := e.Path
		for _, p := range e.PathParams {
			path = strings.Replace(path, ":"+p, "test-"+p, 1)
		}
		fmt.Fprintf(&b, "func Test%s_HappyPath(t *testing.T) {\n\tapp := testApp()\n", e.GoName)
		if e.FromBody && len(e.Input) > 0 {
			fmt.Fprintf(&b, "\treq := httptest.NewRequest(%q, %q, strings.NewReader(`%s`))\n\treq.Header.Set(\"Content-Type\", \"application/json\")\n", e.Method, path, validJSONBody(e))
		} else {
			fmt.Fprintf(&b, "\treq := httptest.NewRequest(%q, %q, nil)\n", e.Method, path)
		}
		fmt.Fprintf(&b, "\tresp, err := app.Test(req)\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n\tif resp.StatusCode != %d {\n\t\tt.Errorf(\"expected %d, got %%d\", resp.StatusCode)\n\t}\n}\n\n", e.SuccessCode, e.SuccessCode)
	}

	// One validation-failure request: first body endpoint with a required field.
	for _, e := range m.Endpoints {
		if !e.FromBody || len(validatedFields(e.Input)) == 0 {
			continue
		}
		hasRequired := false
		for _, f := range e.Input {
			if f.Required && !f.Optional {
				hasRequired = true
			}
		}
		if !hasRequired {
			continue
		}
		path := e.Path
		for _, p := range e.PathParams {
			path = strings.Replace(path, ":"+p, "test-"+p, 1)
		}
		fmt.Fprintf(&b, "func Test%s_ValidationFailure(t *testing.T) {\n\tapp := testApp()\n\treq := httptest.NewRequest(%q, %q, strings.NewReader(`{}`))\n\treq.Header.Set(\"Content-Type\", \"application/json\")\n\tresp, err := app.Test(req)\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n\tif resp.StatusCode != 422 {\n\t\tt.Errorf(\"expected 422 for invalid input, got %%d\", resp.StatusCode)\n\t}\n}\n\n", e.GoName, e.Method, path)
		break
	}
	return []byte(b.String())
}

// emitServiceTest asserts the skeleton returns ErrNotImplemented everywhere.
func emitServiceTest(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"testing\"\n)\n\nfunc TestServiceSkeleton_ReturnsNotImplemented(t *testing.T) {\n\tsvc := NewService(NewRepository(nil))\n\tctx := context.Background()\n\n", m.ContractFile, m.Package)
	for _, e := range m.Endpoints {
		args := []string{"ctx"}
		for range e.PathParams {
			args = append(args, `"id"`)
		}
		if len(e.Input) > 0 {
			args = append(args, fmt.Sprintf("%sInput{}", e.GoName))
		}
		call := fmt.Sprintf("svc.%s(%s)", e.GoName, strings.Join(args, ", "))
		if len(e.Output) > 0 {
			fmt.Fprintf(&b, "\tif _, err := %s; !errors.Is(err, ErrNotImplemented) {\n\t\tt.Errorf(\"%s: expected ErrNotImplemented, got %%v\", err)\n\t}\n", call, e.GoName)
		} else {
			fmt.Fprintf(&b, "\tif err := %s; !errors.Is(err, ErrNotImplemented) {\n\t\tt.Errorf(\"%s: expected ErrNotImplemented, got %%v\", err)\n\t}\n", call, e.GoName)
		}
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

// emitRepositoryTest asserts construction.
func emitRepositoryTest(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\nimport \"testing\"\n\nfunc TestNewRepository(t *testing.T) {\n\tif NewRepository(nil) == nil {\n\t\tt.Fatal(\"NewRepository returned nil\")\n\t}\n}\n", m.ContractFile, m.Package)
	return []byte(b.String())
}

// emitRoutesTest asserts every contract endpoint is registered.
func emitRoutesTest(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"testing\"\n\n\t\"github.com/gofiber/fiber/v2\"\n)\n\nfunc TestMountWith_RegistersEveryEndpoint(t *testing.T) {\n\tapp := fiber.New()\n\tMountWith(app, fakeService{})\n\n\twant := map[string]bool{\n", m.ContractFile, m.Package)
	for _, e := range m.Endpoints {
		fmt.Fprintf(&b, "\t\t%q: false,\n", e.Method+" "+e.Path)
	}
	b.WriteString("\t}\n\tfor _, r := range app.GetRoutes() {\n\t\tkey := r.Method + \" \" + r.Path\n\t\tif _, ok := want[key]; ok {\n\t\t\twant[key] = true\n\t\t}\n\t}\n\tfor key, seen := range want {\n\t\tif !seen {\n\t\t\tt.Errorf(\"route %s not registered\", key)\n\t\t}\n\t}\n}\n")
	return []byte(b.String())
}
