package gofiber

import (
	"fmt"
	"strings"
)

// serviceSig renders one endpoint's service method signature (sans "func").
// Shape: Name(ctx context.Context[, <pathParam> string]...[, in NameInput])
// (*NameOutput, error) — or just error when the endpoint has no output.
func serviceSig(e endpointSpec) string {
	var params []string
	params = append(params, "ctx context.Context")
	for _, p := range e.PathParams {
		params = append(params, fmt.Sprintf("%s string", p))
	}
	if len(e.Input) > 0 {
		params = append(params, fmt.Sprintf("in %sInput", e.GoName))
	}
	ret := "error"
	if len(e.Output) > 0 {
		ret = fmt.Sprintf("(*%sOutput, error)", e.GoName)
	}
	return fmt.Sprintf("%s(%s) %s", e.GoName, strings.Join(params, ", "), ret)
}

// serviceCallArgs renders the argument list a handler passes to the service.
func serviceCallArgs(e endpointSpec) string {
	args := []string{"c.Context()"}
	for _, p := range e.PathParams {
		args = append(args, p)
	}
	if len(e.Input) > 0 {
		args = append(args, "in")
	}
	return strings.Join(args, ", ")
}

// emitService renders the Service interface plus an editable skeleton
// implementation that wires the repository and returns ErrNotImplemented.
func emitService(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s as an editable skeleton —\n// implement the business logic here; regeneration will not overwrite an\n// edited file (see generated.lock).\npackage %s\n\nimport (\n\t\"context\"\n)\n\n", m.ContractFile, m.Package)

	b.WriteString("// Service is the business-logic seam for the " + m.Contract + " contract.\ntype Service interface {\n")
	for _, e := range m.Endpoints {
		fmt.Fprintf(&b, "\t%s\n", serviceSig(e))
	}
	b.WriteString("}\n\n")

	b.WriteString("type service struct {\n\trepo *Repository\n}\n\n// NewService wires the contract's service skeleton to its repository.\nfunc NewService(repo *Repository) Service {\n\treturn &service{repo: repo}\n}\n\n")

	for _, e := range m.Endpoints {
		fmt.Fprintf(&b, "func (s *service) %s {\n", serviceSig(e))
		if len(e.Output) > 0 {
			b.WriteString("\treturn nil, ErrNotImplemented\n")
		} else {
			b.WriteString("\treturn ErrNotImplemented\n")
		}
		b.WriteString("}\n\n")
	}
	return []byte(b.String())
}

// emitRepository renders the pgx repository skeleton.
func emitRepository(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s as an editable skeleton —\n// implement data access here; regeneration will not overwrite an edited\n// file (see generated.lock).\npackage %s\n\nimport (\n\t\"github.com/jackc/pgx/v5/pgxpool\"\n)\n\n", m.ContractFile, m.Package)
	b.WriteString(`// Repository is the pgx-backed data-access skeleton for the ` + m.Contract + `
// contract. The generated service calls it once you implement both sides.
type Repository struct {
	db *pgxpool.Pool
}

func NewRepository(db *pgxpool.Pool) *Repository {
	return &Repository{db: db}
}
`)
	return []byte(b.String())
}
