package gofiber

import (
	"fmt"
	"strings"
)

// emitMigrations derives one up/down migration pair from the contract's
// types: — one table per object type, snake_case columns, ULID TEXT pks.
// Contract-derived migrations own the 0400–0499 range (Phase 7 PRD).
func emitMigrations(m *model) (up, down []byte) {
	var u, d strings.Builder
	fmt.Fprintf(&u, "-- Code generated by acthur from %s.\n", m.ContractFile)
	fmt.Fprintf(&d, "-- Code generated by acthur from %s.\n", m.ContractFile)

	for _, t := range m.Types {
		table := tableName(t.Name)
		fmt.Fprintf(&u, "\nCREATE TABLE IF NOT EXISTS %s (\n", table)
		var cols []string
		for _, f := range t.Fields {
			col := sqlColumn(f)
			if col == "" {
				continue // arrays/refs are relations, out of scope for the derived table
			}
			cols = append(cols, "    "+col)
		}
		u.WriteString(strings.Join(cols, ",\n"))
		u.WriteString("\n);\n")

		fmt.Fprintf(&d, "\nDROP TABLE IF EXISTS %s;\n", table)
	}
	return []byte(u.String()), []byte(d.String())
}

func tableName(typeName string) string {
	snake := toSnake(typeName)
	if strings.HasSuffix(snake, "s") {
		return snake + "es"
	}
	return snake + "s"
}

func toSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func sqlColumn(f fieldSpec) string {
	var t string
	switch f.BaseType {
	case "ulid", "string", "email", "enum":
		t = "TEXT"
	case "int":
		t = "BIGINT"
	case "bool":
		t = "BOOLEAN"
	case "timestamp":
		t = "TIMESTAMPTZ"
	case "float":
		t = "DOUBLE PRECISION"
	default:
		return ""
	}
	col := f.Name + " " + t
	if f.Name == "id" {
		col += " PRIMARY KEY"
	} else if !f.Optional {
		col += " NOT NULL"
	}
	return col
}
