package gofiber

import (
	"fmt"
	"strings"
)

// emitDTO renders internal/<pkg>/dto.go: contract types, per-endpoint
// input/output structs with constraint-derived Validate methods, and the
// APIError sentinels for every declared contract error.
func emitDTO(m *model) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur from %s. DO NOT EDIT.\npackage %s\n\n", m.ContractFile, m.Package)

	needsFmt := false
	for _, e := range m.Endpoints {
		if len(validatedFields(e.Input)) > 0 {
			needsFmt = true
		}
	}
	var imports []string
	if needsFmt {
		imports = append(imports, `"fmt"`)
	}
	if m.NeedsTime {
		imports = append(imports, `"time"`)
	}
	if len(m.Endpoints) > 0 { // email validation uses strings
		for _, e := range m.Endpoints {
			for _, f := range e.Input {
				if f.BaseType == "email" {
					imports = append(imports, `"strings"`)
					goto done
				}
			}
		}
	}
done:
	if len(imports) > 0 {
		fmt.Fprintf(&b, "import (\n\t%s\n)\n\n", strings.Join(imports, "\n\t"))
	}

	// APIError + sentinels from the contract's declared errors.
	b.WriteString(`// APIError is a contract-declared error a service returns and the
// handler maps to its HTTP status.
type APIError struct {
	Status int    ` + "`json:\"-\"`" + `
	Code   string ` + "`json:\"code\"`" + `
}

func (e *APIError) Error() string { return e.Code }

`)
	for _, ce := range m.Errors {
		fmt.Fprintf(&b, "var Err%s = &APIError{Status: %d, Code: %q}\n", goName(ce.Code), ce.Status, ce.Code)
	}
	b.WriteString("\n// ErrNotImplemented is returned by generated service skeletons.\nvar ErrNotImplemented = &APIError{Status: 501, Code: \"not_implemented\"}\n\n")

	// Contract types.
	for _, t := range m.Types {
		fmt.Fprintf(&b, "type %s struct {\n", t.Name)
		for _, f := range t.Fields {
			fmt.Fprintf(&b, "\t%s %s `json:%q`\n", f.GoName, f.GoType, f.Name)
		}
		b.WriteString("}\n\n")
	}

	// Endpoint input/output structs.
	for _, e := range m.Endpoints {
		if len(e.Input) > 0 {
			fmt.Fprintf(&b, "type %sInput struct {\n", e.GoName)
			for _, f := range e.Input {
				tag := fmt.Sprintf("`json:%q query:%q`", f.Name, f.Name)
				fmt.Fprintf(&b, "\t%s %s %s\n", f.GoName, f.GoType, tag)
			}
			b.WriteString("}\n\n")
			emitValidate(&b, e)
		}
		if len(e.Output) > 0 {
			fmt.Fprintf(&b, "type %sOutput struct {\n", e.GoName)
			for _, f := range e.Output {
				fmt.Fprintf(&b, "\t%s %s `json:%q`\n", f.GoName, f.GoType, f.Name)
			}
			b.WriteString("}\n\n")
		}
	}
	return []byte(b.String())
}

// validatedFields returns the input fields that produce validation code.
func validatedFields(fields []fieldSpec) []fieldSpec {
	var out []fieldSpec
	for _, f := range fields {
		if f.Required || f.MaxLen > 0 || f.BaseType == "email" || f.BaseType == "enum" {
			out = append(out, f)
		}
	}
	return out
}

func emitValidate(b *strings.Builder, e endpointSpec) {
	vf := validatedFields(e.Input)
	fmt.Fprintf(b, "func (in %sInput) Validate() error {\n", e.GoName)
	for _, f := range vf {
		access := "in." + f.GoName
		guardOpen, indent := "", "\t"
		if f.Optional {
			fmt.Fprintf(b, "\tif in.%s != nil {\n", f.GoName)
			access = "(*in." + f.GoName + ")"
			guardOpen, indent = "\t}\n", "\t\t"
		}
		if f.Required && !f.Optional {
			fmt.Fprintf(b, "%sif %s == \"\" {\n%s\treturn fmt.Errorf(\"%s is required\")\n%s}\n", indent, access, indent, f.Name, indent)
		}
		if f.MaxLen > 0 {
			fmt.Fprintf(b, "%sif len(%s) > %d {\n%s\treturn fmt.Errorf(\"%s exceeds max length %d\")\n%s}\n", indent, access, f.MaxLen, indent, f.Name, f.MaxLen, indent)
		}
		if f.BaseType == "email" {
			cond := access + ` != "" && !strings.Contains(` + access + `, "@")`
			if f.Required && !f.Optional {
				cond = `!strings.Contains(` + access + `, "@")`
			}
			fmt.Fprintf(b, "%sif %s {\n%s\treturn fmt.Errorf(\"%s must be a valid email\")\n%s}\n", indent, cond, indent, f.Name, indent)
		}
		if f.BaseType == "enum" {
			fmt.Fprintf(b, "%sswitch %s {\n%scase %s:\n%sdefault:\n%s\treturn fmt.Errorf(\"%s must be one of %s\")\n%s}\n",
				indent, access, indent, quoteList(f.Enum), indent, indent, f.Name, strings.Join(f.Enum, ", "), indent)
		}
		b.WriteString(guardOpen)
	}
	b.WriteString("\treturn nil\n}\n\n")
}

func quoteList(vals []string) string {
	qs := make([]string, len(vals))
	for i, v := range vals {
		qs[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(qs, ", ")
}
