package gofiber

import (
	"fmt"
	"strings"

	"github.com/acthur/acthur/internal/plugin"
)

// GenerateModel turns `acthur generate model <Name> <field:type>...` input
// into a model struct under internal/models/, a test beside it, and a
// contract-range migration — the same 0400–0499 range from-contract uses
// (the CLI renumbers to the next free slot).
func GenerateModel(name string, rawFields map[string]string, ctx plugin.GeneratorContext) ([]plugin.GeneratedFile, error) {
	if name == "" {
		return nil, fmt.Errorf("model name is required")
	}
	fields, err := buildFields(rawFields)
	if err != nil {
		return nil, fmt.Errorf("model %s: %w", name, err)
	}
	if len(fields) == 0 {
		return nil, fmt.Errorf("model %s: at least one field:type argument is required", name)
	}

	// Every model gets a ULID text pk unless the caller declared id.
	hasID := false
	for _, f := range fields {
		if f.Name == "id" {
			hasID = true
		}
	}
	if !hasID {
		idField, _ := parseField("id", "ulid")
		fields = append([]fieldSpec{idField}, fields...)
	}

	snake := toSnake(name)
	m := &model{
		Contract:     snake,
		Package:      "models",
		ContractFile: fmt.Sprintf("`acthur generate model %s`", name),
		Types:        []typeSpec{{Name: name, Fields: fields}},
	}
	m.NeedsTime = anyTimestamp(m)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by acthur (%s). DO NOT EDIT.\npackage models\n\n", strings.Trim(m.ContractFile, "`"))
	if m.NeedsTime {
		b.WriteString("import \"time\"\n\n")
	}
	fmt.Fprintf(&b, "type %s struct {\n", name)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%s %s `json:%q`\n", f.GoName, f.GoType, f.Name)
	}
	b.WriteString("}\n")

	var tb strings.Builder
	fmt.Fprintf(&tb, "// Code generated by acthur (%s). DO NOT EDIT.\npackage models\n\nimport (\n\t\"encoding/json\"\n\t\"testing\"\n)\n\nfunc Test%s_JSONRoundTrip(t *testing.T) {\n\tin := %s{}\n\tdata, err := json.Marshal(in)\n\tif err != nil {\n\t\tt.Fatalf(\"marshal: %%v\", err)\n\t}\n\tvar out %s\n\tif err := json.Unmarshal(data, &out); err != nil {\n\t\tt.Fatalf(\"unmarshal: %%v\", err)\n\t}\n}\n", strings.Trim(m.ContractFile, "`"), name, name, name)

	up, down := emitMigrations(m)
	return []plugin.GeneratedFile{
		{Path: "internal/models/" + snake + ".go", Content: []byte(b.String()), Overwrite: true},
		{Path: "internal/models/" + snake + "_test.go", Content: []byte(tb.String()), Overwrite: true},
		{Path: "migrations/0400_" + snake + ".up.sql", Content: up, Overwrite: false},
		{Path: "migrations/0400_" + snake + ".down.sql", Content: down, Overwrite: false},
	}, nil
}
