// Package skillgen generates a Claude Code skill scaffold
// (.claude/skills/<name>/SKILL.md) from the live project graph — the
// "how do I do X in this specific project?" procedure file described in
// acthur-prd.md §17.3/17.4, as opposed to internal/generate/aicontext's
// static "what is this project?" description.
package skillgen

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/acthurhq/acthur/internal/config"
	"github.com/acthurhq/acthur/internal/graph"
	"github.com/acthurhq/acthur/internal/plugin"
)

// nameRe matches a valid skill name: lowercase kebab-case, matching the
// convention every skill on disk under .claude/skills already uses.
var nameRe = regexp.MustCompile(`^[a-z][a-z0-9]*(-[a-z0-9]+)*$`)

// Generate renders .claude/skills/<name>/SKILL.md, deriving its body from
// cfg and the built graph g: adapters in play, active plugins, and the
// project's own acthur commands — so the skill never describes a stack the
// project doesn't actually have.
func Generate(cfg *config.Config, g *graph.Graph, name string) (plugin.GeneratedFile, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return plugin.GeneratedFile{}, fmt.Errorf("skill name must not be empty")
	}
	if !nameRe.MatchString(name) {
		return plugin.GeneratedFile{}, fmt.Errorf(
			"invalid skill name %q — expected lowercase kebab-case (e.g. \"create-endpoint\")", name)
	}

	adapters := serviceAdapters(g)
	plugins := pluginNames(cfg)

	description := fmt.Sprintf(
		"Project-specific skill for %s, generated by `acthur generate skill %s`. Use when working on this task in this codebase.",
		projectLabel(cfg), name,
	)

	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "name: %s\n", name)
	fmt.Fprintf(&b, "description: %s\n", description)
	b.WriteString("---\n\n")

	fmt.Fprintf(&b, "# %s\n\n", titleCase(name))
	b.WriteString("Generated by `acthur generate skill` — a starting point tied to this " +
		"project's actual graph. Fill in the task-specific steps; the sections below are " +
		"derived facts you can rely on, not guesses.\n\n")

	b.WriteString("## Project\n\n")
	fmt.Fprintf(&b, "- **Project**: %s\n", projectLabel(cfg))
	if len(adapters) > 0 {
		fmt.Fprintf(&b, "- **Service adapters**: %s\n", strings.Join(adapters, ", "))
	}
	if len(plugins) > 0 {
		fmt.Fprintf(&b, "- **Active plugins**: %s\n", strings.Join(plugins, ", "))
	} else {
		b.WriteString("- **Active plugins**: none\n")
	}
	b.WriteString("\n")

	b.WriteString("## Conventions\n\n")
	b.WriteString("- The graph in `acthur.yml` is the source of truth for services, infra, " +
		"and their edges — run `acthur graph show` to see it live, `acthur graph validate` " +
		"before committing changes to it.\n")
	b.WriteString("- Data flowing between two nodes must be declared on a `data_flow` edge " +
		"with a contract under `contracts/*.contract.yml`; `acthur generate from-contract` " +
		"and `acthur generate model` turn a contract or field list into code.\n")
	b.WriteString("- Everything acthur writes for you is tracked in `generated.lock` — hand " +
		"edits are detected and preserved on the next generate run rather than clobbered.\n")
	b.WriteString("- `acthur dev` runs the live dev graph (hot reload, DNS, proxy); " +
		"`acthur build`/`acthur test` drive every node through its adapter's own toolchain.\n\n")

	b.WriteString("## Steps\n\n")
	b.WriteString("1. Describe the task this skill should trigger on.\n")
	b.WriteString("2. List the exact commands/files involved for this project (see Project " +
		"section above for the real adapters and plugins in play).\n")
	b.WriteString("3. Note anything project-specific that would otherwise have to be " +
		"re-discovered by reading code.\n")

	return plugin.GeneratedFile{
		Path:      ".claude/skills/" + name + "/SKILL.md",
		Content:   []byte(b.String()),
		Overwrite: false, // this is a starting point for the user to fill in — never clobber
	}, nil
}

func projectLabel(cfg *config.Config) string {
	if cfg.Project == "" {
		return "this acthur project"
	}
	return cfg.Project
}

// serviceAdapters returns the sorted, de-duplicated set of adapters used by
// service nodes in the graph.
func serviceAdapters(g *graph.Graph) []string {
	seen := map[string]bool{}
	for _, n := range g.Nodes() {
		if n.Type == config.NodeTypeService && n.Adapter != "" {
			seen[n.Adapter] = true
		}
	}
	out := make([]string, 0, len(seen))
	for a := range seen {
		out = append(out, a)
	}
	sort.Strings(out)
	return out
}

func pluginNames(cfg *config.Config) []string {
	out := make([]string, 0, len(cfg.Plugins))
	for _, p := range cfg.Plugins {
		out = append(out, p.Name)
	}
	sort.Strings(out)
	return out
}

func titleCase(kebab string) string {
	parts := strings.Split(kebab, "-")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, " ")
}
