// Package ci generates CI/CD pipeline configuration from the project graph.
// acthur-prd.md §35 describes multiple targets (GitHub Actions, GitLab CI,
// CircleCI); this package implements github-actions — the default and the
// only target requested for this slice. Generate returns a pointed,
// non-silent error for any other target rather than emitting a stub.
package ci

import (
	"fmt"
	"strings"

	"github.com/acthur/acthur/internal/config"
	"github.com/acthur/acthur/internal/plugin"
	"gopkg.in/yaml.v3"
)

// goVersion pins the Go toolchain version the generated workflow installs.
// Matches this repo's go.mod (module github.com/acthur/acthur, go 1.22) —
// acthur itself is a Go binary regardless of which adapters a project uses,
// since `acthur build`/`acthur test` drive every adapter's own toolchain.
const goVersion = "1.22"

// installScript is acthur's documented distribution channel
// (acthur-prd.md §"Installation": `curl -fsSL https://install.acthur.dev | sh`).
const installScript = "curl -fsSL https://install.acthur.dev | sh"

// Target identifies which CI provider's config to emit.
type Target string

const (
	TargetGitHubActions Target = "github-actions"
)

// SupportedTargets returns the target keys Generate accepts.
func SupportedTargets() []string {
	return []string{string(TargetGitHubActions)}
}

// ---------------------------------------------------------------------------
// GitHub Actions workflow shape — a typed mirror of the schema GitHub Actions
// expects, marshaled with yaml.v3 so the output is guaranteed syntactically
// valid YAML rather than hand-built string concatenation.
// ---------------------------------------------------------------------------

type ghWorkflow struct {
	Name string           `yaml:"name"`
	On   map[string]any   `yaml:"on"`
	Jobs map[string]ghJob `yaml:"jobs"`
}

type ghJob struct {
	RunsOn string   `yaml:"runs-on"`
	Steps  []ghStep `yaml:"steps"`
}

type ghStep struct {
	Name string         `yaml:"name,omitempty"`
	Uses string         `yaml:"uses,omitempty"`
	With map[string]any `yaml:"with,omitempty"`
	Run  string         `yaml:"run,omitempty"`
}

// Generate renders the CI workflow file for target. cfg supplies the
// project name used in the workflow's display name.
func Generate(cfg *config.Config, target string) (plugin.GeneratedFile, error) {
	t := Target(strings.ToLower(strings.TrimSpace(target)))
	if t == "" {
		t = TargetGitHubActions
	}
	if t != TargetGitHubActions {
		return plugin.GeneratedFile{}, fmt.Errorf(
			"unsupported ci target %q — supported: %s (gitlab-ci and circleci are tracked but not yet implemented)",
			target, strings.Join(SupportedTargets(), ", "),
		)
	}

	project := cfg.Project
	if project == "" {
		project = "acthur project"
	}

	wf := ghWorkflow{
		Name: fmt.Sprintf("Acthur CI — %s", project),
		On: map[string]any{
			"push":         nil,
			"pull_request": nil,
		},
		Jobs: map[string]ghJob{
			"build-and-test": {
				RunsOn: "ubuntu-latest",
				Steps: []ghStep{
					{Name: "Checkout", Uses: "actions/checkout@v4"},
					{
						Name: "Set up Go",
						Uses: "actions/setup-go@v5",
						With: map[string]any{
							"go-version": goVersion,
							"cache":      true,
						},
					},
					{Name: "Install acthur", Run: installScript},
					{Name: "acthur graph validate", Run: "acthur graph validate"},
					{Name: "acthur build", Run: "acthur build"},
					{Name: "acthur test", Run: "acthur test"},
				},
			},
		},
	}

	data, err := yaml.Marshal(wf)
	if err != nil {
		return plugin.GeneratedFile{}, fmt.Errorf("marshaling github actions workflow: %w", err)
	}

	// Self-check: the marshaled bytes must parse back as valid YAML before
	// this ever reaches disk — catches a generator bug rather than shipping
	// broken CI config.
	var roundTrip map[string]any
	if err := yaml.Unmarshal(data, &roundTrip); err != nil {
		return plugin.GeneratedFile{}, fmt.Errorf("generated github actions workflow is not valid YAML: %w", err)
	}

	header := "# Generated by `acthur generate ci` — regenerate via that command instead of hand-editing.\n"
	content := header + string(data)

	return plugin.GeneratedFile{
		Path:      ".github/workflows/acthur.yml",
		Content:   []byte(content),
		Overwrite: true,
	}, nil
}
