// Package aicontext generates AI coding-tool context files from the live
// Acthur graph, config, and contract registry — the "what is this project?"
// document described in acthur-prd.md §17.3, as opposed to the
// task-procedure skill files internal/generate/skillgen produces.
//
// Context files are derived, not authored: every run recomputes the file
// from cfg + graph + contracts, so it is always accurate and never drifts
// from the declared system. Output is deterministic — nodes, edges, and
// contracts are all sorted before rendering — so re-running with no
// underlying change produces byte-identical output (required for
// internal/generate.WriteFiles' unchanged-since-last-generated check to work).
package aicontext

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/acthurhq/acthur/internal/config"
	"github.com/acthurhq/acthur/internal/contract"
	"github.com/acthurhq/acthur/internal/graph"
	"github.com/acthurhq/acthur/internal/plugin"
)

// Tool identifies which AI coding tool's context file convention to emit.
type Tool string

const (
	ToolClaude Tool = "claude"
	ToolCursor Tool = "cursor"
)

// toolPaths maps each supported tool to the file it owns.
// acthur-prd.md §17.2 lists more tools than this; only the two most common
// are implemented here — Generate returns a pointed error naming both for
// anything else, so adding a new tool later is additive, not a breaking change.
var toolPaths = map[Tool]string{
	ToolClaude: "CLAUDE.md",
	ToolCursor: ".cursorrules",
}

// SupportedTools returns the tool keys Generate accepts, sorted.
func SupportedTools() []string {
	out := make([]string, 0, len(toolPaths))
	for t := range toolPaths {
		out = append(out, string(t))
	}
	sort.Strings(out)
	return out
}

// Generate renders the context file for the given tool from cfg, the built
// graph g, and the project's contract registry (reg may be nil or empty —
// contracts are optional). Returns a single plugin.GeneratedFile ready for
// internal/generate.WriteFiles.
func Generate(cfg *config.Config, g *graph.Graph, reg *contract.Registry, tool string) (plugin.GeneratedFile, error) {
	t := Tool(strings.ToLower(strings.TrimSpace(tool)))
	if t == "" {
		t = ToolClaude
	}
	path, ok := toolPaths[t]
	if !ok {
		return plugin.GeneratedFile{}, fmt.Errorf(
			"unsupported ai-context tool %q — supported: %s",
			tool, strings.Join(SupportedTools(), ", "),
		)
	}

	var b strings.Builder
	writeHeader(&b, cfg, t)
	writeNodes(&b, g)
	writeEdges(&b, g)
	writeContracts(&b, reg)
	writePlugins(&b, cfg)
	writeFooter(&b)

	return plugin.GeneratedFile{
		Path:      path,
		Content:   []byte(b.String()),
		Overwrite: true,
	}, nil
}

func writeHeader(b *strings.Builder, cfg *config.Config, t Tool) {
	project := cfg.Project
	if project == "" {
		project = "(unnamed project)"
	}
	fmt.Fprintf(b, "# %s — Acthur Project Context\n\n", project)
	fmt.Fprintf(b, "Generated by `acthur generate ai-context` for %s. This file describes ", t)
	b.WriteString("the live system graph — services, adapters, data-flow edges, contracts, " +
		"and plugins — as declared in `acthur.yml`. It is derived, not hand-authored: " +
		"re-run `acthur generate ai-context` after changing the graph rather than editing " +
		"this file directly.\n\n")
	b.WriteString("Acthur is a runtime graph operating system: backend services, frontends, " +
		"and infrastructure are first-class nodes in a live directed acyclic graph (DAG). " +
		"Every edge below is an enforced relationship, not documentation of intent.\n\n")
}

func writeNodes(b *strings.Builder, g *graph.Graph) {
	nodes := g.Nodes()
	sort.Slice(nodes, func(i, j int) bool { return nodes[i].ID < nodes[j].ID })

	b.WriteString("## Nodes\n\n")
	if len(nodes) == 0 {
		b.WriteString("_No nodes declared._\n\n")
		return
	}
	b.WriteString("| ID | Type | Adapter | Role | Port | Dev URL |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, n := range nodes {
		port := ""
		if n.Port != 0 {
			port = strconv.Itoa(n.Port)
		}
		role := string(n.Role)
		if role == "" {
			role = "-"
		}
		devURL := n.DevURL
		if devURL == "" {
			devURL = "-"
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %s |\n",
			n.ID, n.Type, n.Adapter, role, orDash(port), devURL)
	}
	b.WriteString("\n")
}

func writeEdges(b *strings.Builder, g *graph.Graph) {
	edges := append([]*graph.Edge(nil), g.Edges()...)
	sort.Slice(edges, func(i, j int) bool {
		if edges[i].From != edges[j].From {
			return edges[i].From < edges[j].From
		}
		if edges[i].To != edges[j].To {
			return edges[i].To < edges[j].To
		}
		return edges[i].Type < edges[j].Type
	})

	b.WriteString("## Edges\n\n")
	if len(edges) == 0 {
		b.WriteString("_No edges declared._\n\n")
		return
	}
	for _, e := range edges {
		extra := ""
		if len(e.Contracts) > 0 {
			extra = fmt.Sprintf(" [%s]", strings.Join(e.Contracts, ", "))
		}
		if len(e.Events) > 0 {
			extra += fmt.Sprintf(" events=[%s]", strings.Join(e.Events, ", "))
		}
		fmt.Fprintf(b, "- `%s` → `%s` (%s)%s\n", e.From, e.To, e.Type, extra)
	}
	b.WriteString("\n")
}

func writeContracts(b *strings.Builder, reg *contract.Registry) {
	b.WriteString("## Contracts\n\n")
	if reg == nil {
		b.WriteString("_No contract registry loaded._\n\n")
		return
	}
	contracts := reg.All()
	if len(contracts) == 0 {
		b.WriteString("_No contracts declared under `contracts/`._\n\n")
		return
	}
	sort.Slice(contracts, func(i, j int) bool {
		if contracts[i].Name != contracts[j].Name {
			return contracts[i].Name < contracts[j].Name
		}
		return contracts[i].Version < contracts[j].Version
	})
	for _, c := range contracts {
		fmt.Fprintf(b, "- **%s** v%s (%s) — %d endpoint(s), %d type(s)\n",
			c.Name, c.Version, c.Transport, len(c.Endpoints), len(c.Types))
	}
	b.WriteString("\n")
}

func writePlugins(b *strings.Builder, cfg *config.Config) {
	b.WriteString("## Plugins\n\n")
	if len(cfg.Plugins) == 0 {
		b.WriteString("_No plugins installed._\n\n")
		return
	}
	names := make([]string, 0, len(cfg.Plugins))
	for _, p := range cfg.Plugins {
		names = append(names, p.Name)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(b, "- `%s`\n", n)
	}
	b.WriteString("\n")
}

func writeFooter(b *strings.Builder) {
	b.WriteString("## Conventions\n\n")
	b.WriteString("- Every generated file is tracked in `generated.lock`; hand-edits are " +
		"detected and preserved (regeneration skips files that diverged from what acthur " +
		"last wrote, unless the file has a merge marker).\n")
	b.WriteString("- Contracts are the only thing allowed to flow across a `data_flow` edge; " +
		"add one under `contracts/<name>.contract.yml` and reference it on the edge before " +
		"wiring two services together.\n")
	b.WriteString("- Run `acthur graph validate` after editing `acthur.yml` — it is the single " +
		"authority for structural correctness (cycles, orphans, unresolved adapters).\n")
}

func orDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}
